kind: pipeline
type: docker
name: drone plugin deployment manager

steps:

  - name: deploy-bash-plugin
    image: docker:dind # public docker image
    volumes:
    - name: dockersock
      path: /var/run
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - sleep 5 # give docker enough time to start
      - echo "The deploys the bash plugin"
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - docker build -t alsaheem/webhook . -f drone_plugins/bash_plugin/Dockerfile
      - docker push alsaheem/webhook

  - name: deploy-python-plugin
    image: docker:dind # public docker image
    volumes:
    - name: dockersock
      path: /var/run
    environment:
      DOCKER_USERNAME:
        from_secret: docker_username
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - sleep 5 # give docker enough time to start
      - echo "The deploys the python plugin"
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - docker build -t alsaheem/healthchecker . -f drone_plugins/healthchecker/Dockerfile
      - docker push alsaheem/healthchecker