kind: pipeline
type: docker
name: default

steps:
  - name: webhook
    image: alsaheem/webhook
    settings:
      url: http://hook.acme.com
      method: post
      body: |
              hello world